# Generated by Django 4.2.13 on 2024-05-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=200)),
                ("mp3_file", models.FileField(upload_to="podcasts/")),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
